### ISSUE TITLE
Seed phrase unscramble metamask

### ISSUE THREAD

**Issue by Bl8k38500** [ethanrushh/MetaMask-Seed-Unscrambler#1]

**Comment by ethanrushh** [comment]
I'll make another version with a GUI this time. Please wait a few days while I create a version 2.0 and try that.

**Comment by ethanrushh** [comment]
I have uploaded a new 2.0 release which should be much easier to use. Give the new builds a try on your platform of choice. I hope you get it back! As always if you like my work and would like to share anything you may be able to recover, please donate anything you wish to at 0x2F50B7A73D7065a672bB0eb97fB4e3DAb391CC23
